---
# tasks file for k8s-master
- name: Installing docker and iproute-tc Package
  package: 
    name:
    - docker
    - iproute-tc
    state: present

- name: Configuring Yum repo for k8s
  yum_repository:
    name: kubernetes
    description: Yum for k8s
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: 
    - kubelet 
    - kubeadm 
    - kubectl

- name: Installing kubeadm
  yum:
    name: kubeadm
    disable_excludes: kubernetes

- name: Enabling docker and kubelet services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kubelet
    - docker

- name: Pulling all Required images
  shell: kubeadm config images pull

- name: Copying content of the daemon.json file
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: Restarting Docker service
  service:
    name: docker
    state: restarted

- name: Copying k8s.conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf

- name: Refreshing sysctl 
  shell: "sysctl --system"

- name: Starting kubeadm service
  shell: "kubeadm init --pod-network-cidr={{ cidr }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"

- name: Creating .kube Directory
  file:
    path: $HOME/.kube
    state: directory

- name: Copying file config file
  shell: "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

- name: Installing Addons
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

